# Generated by Django 5.1.6 on 2025-03-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsakey',
            name='output_private_key',
        ),
        migrations.AddField(
            model_name='chat',
            name='encrypt_algorithm',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
