# Generated by Django 5.1.6 on 2025-03-06 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_remove_rsakey_output_n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='encrypt_algorithm',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='algorithm', to='messenger.encryptalgorithm'),
        ),
    ]
